# Generated by Django 3.2.8 on 2022-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreanc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
