# Generated by Django 3.2.8 on 2022-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0002_alter_koreanc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biblekhrv',
            old_name='field1',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='biblekhrv',
            old_name='field2',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='biblekhrv',
            old_name='field3',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='biblekhrv',
            old_name='field4',
            new_name='verse',
        ),
        migrations.AlterField(
            model_name='biblekhrv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
