# Generated by Django 3.2.8 on 2022-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0003_auto_20220629_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='KSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Book_No', models.CharField(max_length=100)),
                ('Chapter', models.CharField(max_length=100)),
                ('Verse', models.CharField(max_length=100)),
                ('Text', models.TextField()),
            ],
        ),
    ]
