# Generated by Django 3.2.8 on 2022-06-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0004_ksv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hebrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.CharField(max_length=100)),
                ('Verse', models.CharField(max_length=100)),
                ('Chapter', models.CharField(max_length=100)),
                ('Text', models.TextField()),
            ],
        ),
    ]
