# Generated by Django 3.2.8 on 2022-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0006_chines_bible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korean_Bible_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.CharField(max_length=100)),
                ('Book_No', models.CharField(max_length=100)),
                ('Chapter', models.CharField(max_length=100)),
                ('Verse', models.CharField(max_length=100)),
                ('Text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Hebrew',
            new_name='Hebrew_Bible',
        ),
        migrations.DeleteModel(
            name='KoreanC',
        ),
        migrations.DeleteModel(
            name='KSV',
        ),
    ]
