# Generated by Django 3.2.8 on 2022-07-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0009_english_esv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hebrew_Bible',
        ),
    ]
