# Generated by Django 3.2.8 on 2022-07-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0011_hebrew_bible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Bible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_No', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
