# Generated by Django 3.2.8 on 2022-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0014_auto_20220708_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='english_esv',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='korean_bible_c',
            name='tables',
        ),
        migrations.AddField(
            model_name='daily_bible',
            name='chinses',
            field=models.ManyToManyField(to='bibleapp.Chines_Bible'),
        ),
        migrations.AddField(
            model_name='daily_bible',
            name='esv',
            field=models.ManyToManyField(to='bibleapp.English_ESV'),
        ),
    ]
