# Generated by Django 3.2.8 on 2022-07-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0016_auto_20220708_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Korean_Bible_C',
            new_name='Korean_Bible',
        ),
        migrations.DeleteModel(
            name='BibleKhrv',
        ),
    ]
