# Generated by Django 3.2.8 on 2022-07-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0017_auto_20220713_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='korean_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_ID', models.IntegerField()),
                ('Book', models.CharField(max_length=50)),
            ],
        ),
    ]
