# Generated by Django 3.2.8 on 2022-07-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0020_auto_20220720_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='profiel_ima',
            new_name='profiel_img',
        ),
    ]
