# Generated by Django 3.2.8 on 2022-07-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0021_rename_profiel_ima_user_profile_profiel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='profiel_img',
            new_name='profile_img',
        ),
    ]
