# Generated by Django 3.2.8 on 2022-08-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0023_auto_20220803_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_meditation',
            name='private',
        ),
        migrations.RemoveField(
            model_name='my_meditation',
            name='public',
        ),
        migrations.AddField(
            model_name='my_meditation',
            name='choice',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
