# Generated by Django 3.2.8 on 2022-08-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0024_auto_20220803_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_meditation',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
