# Generated by Django 3.2.8 on 2022-08-05 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bibleapp', '0028_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_meditation',
            name='like',
            field=models.ManyToManyField(related_name='meditation_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
