# Generated by Django 3.2.8 on 2022-08-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0029_my_meditation_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_meditation',
            old_name='like',
            new_name='likes',
        ),
    ]
