# Generated by Django 3.2.8 on 2022-08-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0031_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=b'I01\n', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'DateSave',
            },
        ),
    ]
