# Generated by Django 3.2.8 on 2022-08-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0033_customsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_meditation',
            name='scripture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
