# Generated by Django 3.2.8 on 2022-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0034_my_meditation_scripture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_meditation',
            name='scripture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
