# Generated by Django 3.2.8 on 2022-11-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0036_addevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevents',
            name='end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addevents',
            name='start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
