# Generated by Django 3.2.8 on 2022-12-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0040_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='living_life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_No', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
    ]
