# Generated by Django 3.2.8 on 2023-01-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0041_living_life'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsetting',
            old_name='lang',
            new_name='lang_1',
        ),
        migrations.AddField(
            model_name='customsetting',
            name='lang_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
